version: '3.8'

services:
  traefik:
    # image: traefik:v2.10
    image: traefik:v3.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=kayuv09@yahoo.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--global.sendanonymoususage=false"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    networks:
      - app-network

  frontend:
    build: ./frontend
    environment:
      - PORT=8080
      - AUTH_API_ADDRESS=http://auth-api:8081
      - TODOS_API_ADDRESS=http://todos-api:8082
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=(Host(`hng.eazypro.net`) || Host(`localhost`)) && PathPrefix(`/api/auth`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.middlewares=redirect-to-https"
      - "traefik.http.routers.frontend-secure.rule=(Host(`hng.eazypro.net`) || Host(`localhost`)) && PathPrefix(`/api/auth`)"
      - "traefik.http.routers.frontend-secure.entrypoints=websecure"
      - "traefik.http.routers.frontend-secure.tls=true"
      - "traefik.http.routers.frontend-secure.tls.certresolver=myresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"
    networks:
      - app-network
    depends_on:
      - auth-api
      - todos-api

  auth-api:
    build: ./auth-api
    environment:
      - AUTH_API_PORT=8081
      - JWT_SECRET=myfancysecret
      - USERS_API_ADDRESS=http://users-api:8083
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-api.rule=(Host(`hng.eazypro.net`) || Host(`localhost`)) && PathPrefix(`/api/auth`)"
      - "traefik.http.routers.auth-api.entrypoints=web"
      - "traefik.http.routers.auth-api.middlewares=redirect-to-https"
      - "traefik.http.routers.auth-api-secure.rule=(Host(`hng.eazypro.net`) || Host(`localhost`)) && PathPrefix(`/api/auth`)"
      - "traefik.http.routers.auth-api-secure.entrypoints=websecure"
      - "traefik.http.routers.auth-api-secure.tls=true"
      - "traefik.http.routers.auth-api-secure.tls.certresolver=myresolver"
      - "traefik.http.middlewares.auth-strip.stripprefix.prefixes=/api/auth"
      - "traefik.http.routers.auth-api.middlewares=auth-strip"
      - "traefik.http.routers.auth-api-secure.middlewares=auth-strip"
      - "traefik.http.services.auth-api.loadbalancer.server.port=8081"
    networks:
      - app-network
    depends_on:
      - users-api

  todos-api:
    build: ./todos-api
    environment:
      - JWT_SECRET=myfancysecret
      - REDIS_HOST=redis-queue
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todos-api.rule=(Host(`hng.eazypro.net`) || Host(`localhost`)) && PathPrefix(`/api/todos`)"
      - "traefik.http.routers.todos-api.entrypoints=web"
      - "traefik.http.routers.todos-api.middlewares=redirect-to-https"
      - "traefik.http.routers.todos-api-secure.rule=(Host(`hng.eazypro.net`) || Host(`localhost`)) && PathPrefix(`/api/todos`)"
      - "traefik.http.routers.todos-api-secure.entrypoints=websecure"
      - "traefik.http.routers.todos-api-secure.tls=true"
      - "traefik.http.routers.todos-api-secure.tls.certresolver=myresolver"
      - "traefik.http.middlewares.todos-strip.stripprefix.prefixes=/api/todos"
      - "traefik.http.routers.todos-api.middlewares=todos-strip"
      - "traefik.http.routers.todos-api-secure.middlewares=todos-strip"
      - "traefik.http.services.todos-api.loadbalancer.server.port=8082"
    networks:
      - app-network
    depends_on:
      - redis-queue

  users-api:
    build: ./users-api
    environment:
      - SERVER_PORT=8083
      - JWT_SECRET=myfancysecret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users-api.rule=(Host(`hng.eazypro.net`) || Host(`localhost`)) && PathPrefix(`/api/users`)"
      - "traefik.http.routers.users-api.entrypoints=web"
      - "traefik.http.routers.users-api.middlewares=redirect-to-https"
      - "traefik.http.routers.users-api-secure.rule=(Host(`hng.eazypro.net`) || Host(`localhost`)) && PathPrefix(`/api/users`)"
      - "traefik.http.routers.users-api-secure.entrypoints=websecure"
      - "traefik.http.routers.users-api-secure.tls=true"
      - "traefik.http.routers.users-api-secure.tls.certresolver=myresolver"
      - "traefik.http.middlewares.users-strip.stripprefix.prefixes=/api/users"
      - "traefik.http.routers.users-api.middlewares=users-strip"
      - "traefik.http.routers.users-api-secure.middlewares=users-strip"
      - "traefik.http.services.users-api.loadbalancer.server.port=8083"
    networks:
      - app-network

  log-message-processor:
    build: ./log-message-processor
    environment:
      - REDIS_HOST=redis-queue
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    networks:
      - app-network
    depends_on:
      - redis-queue

  redis-queue:
    # image: redis:7-alpine
    image: redis:8-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - app-network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - app-network

volumes:
  redis-data:
  letsencrypt:

networks:
  app-network:
    driver: bridge